export const mainServices = [
  {
    id: 'wordpress-services',
    emoji: '🌐',
    title: 'WordPress Services',
    subtitle: 'Powerful, SEO-optimized WordPress websites, custom themes, plugins, and WooCommerce stores.',
    description: 'We build powerful, SEO-optimized WordPress websites, custom themes, plugins, and WooCommerce stores tailored to your business needs. From simple blogs to complex eCommerce platforms, our WordPress solutions are scalable, secure, and built for performance.',
    benefits: ['Custom WordPress Theme Development', 'Plugin Development & Customization', 'WooCommerce Store Setup', 'WordPress Maintenance & SEO'],
    ideal: 'Businesses of all sizes needing a professional, scalable WordPress website, online store, or custom functionality.',
  },
  {
    id: 'react-nextjs-development',
    emoji: '⚛️',
    title: 'React & Next.js Development',
    subtitle: 'Modern, high-performance web applications built with React, Next.js, and Tailwind CSS.',
    description: 'Reliable, professional, and search engine friendly web solutions using modern JAMStack technology. We specialize in React, Next.js, and Tailwind CSS to deliver blazing-fast, SEO-optimized web applications with exceptional user experiences.',
    benefits: ['Tailwind CSS, Bootstrap & MUI', 'RESTful APIs and GraphQL', 'Prisma, MySQL & SQLite', 'Authentication & Authorization'],
    ideal: 'Startups and businesses wanting modern, high-performance web applications with excellent SEO and developer experience.',
  },
];

export const ugcServices = [
  {
    id: 'product-cgi-ads',
    emoji: '🎬',
    title: 'Product CGI Ads',
    subtitle: 'Bring your products to life with stunning 3D CGI animations that capture attention and increase conversions.',
    description: 'Our 3D CGI product ads transform your products into cinematic visual experiences. Using advanced rendering techniques, we create photorealistic animations that highlight every angle, feature, and detail — making your products impossible to ignore.',
    benefits: ['Photorealistic 3D rendering', 'Cinematic visual storytelling', 'Multi-angle product showcase', 'Attention-grabbing animations'],
    ideal: 'Brands launching new products or wanting premium, high-impact visual content for social media and TV commercials.',
  },
  {
    id: 'ugc-video-ads',
    emoji: '📱',
    title: 'UGC Video Ads',
    subtitle: 'Authentic creator-style videos that build trust, boost engagement, and drive more sales.',
    description: 'User-generated content videos feel real, relatable, and trustworthy. Our team produces authentic creator-style content that blends seamlessly into social feeds, driving higher engagement and conversion rates than traditional polished ads.',
    benefits: ['Authentic creator-style content', 'Higher social media engagement', 'Faster customer trust', 'Platform-native feel'],
    ideal: 'eCommerce brands, D2C companies, and startups looking for cost-effective, high-performing ad creatives.',
  },
  {
    id: 'fashion-brand-ads',
    emoji: '👗',
    title: 'Fashion Brand Ads',
    subtitle: 'Showcase your fashion collection with premium lifestyle videos that inspire customers to buy.',
    description: 'Fashion is visual, and your video content needs to reflect the quality and style of your brand. We produce stunning lifestyle fashion videos that showcase your collection in the best light — from lookbooks to campaign shoots.',
    benefits: ['Premium lifestyle production', 'Professional model coordination', 'Trend-focused styling', 'Multi-outfit showcases'],
    ideal: 'Fashion brands, clothing lines, and apparel retailers launching new collections or seasonal campaigns.',
  },
  {
    id: 'beauty-skincare-ads',
    emoji: '💄',
    title: 'Beauty & Skincare Ads',
    subtitle: 'Elegant, high-converting beauty videos designed to highlight every detail of your products.',
    description: 'Beauty and skincare products demand close-up detail and elegant presentation. Our beauty ad videos use macro shots, flawless lighting, and smooth transitions to make your products look their absolute best.',
    benefits: ['Macro close-up shots', 'Flawless skincare lighting', 'Before/after demonstrations', 'Elegant brand presentation'],
    ideal: 'Beauty brands, skincare companies, and cosmetics lines advertising on Instagram, TikTok, and YouTube.',
  },
  {
    id: 'food-commercial-ads',
    emoji: '🍔',
    title: 'Food Commercial Ads',
    subtitle: 'Mouth-watering food videos that make every dish irresistible and unforgettable.',
    description: 'Food is all about appetite appeal. Our food commercial videos use expert styling, sizzling close-ups, and cinematic pacing to make every dish look delicious and drive cravings — and orders.',
    benefits: ['Expert food styling', 'Sizzling close-up shots', 'Appetite appeal focus', 'Restaurant & brand storytelling'],
    ideal: 'Restaurants, food brands, ghost kitchens, and meal delivery services advertising on social media.',
  },
  {
    id: 'beverage-brand-ads',
    emoji: '🥤',
    title: 'Beverage Brand Ads',
    subtitle: 'Refreshing commercial videos that bring your drinks to life and increase brand awareness.',
    description: 'From carbonated drinks to health beverages, we create refreshing, high-energy videos that capture the essence of your brand. Each frame is crafted to make your beverage look irresistible.',
    benefits: ['High-energy visuals', 'Refreshing aesthetic', 'Brand storytelling', 'Product-in-motion focus'],
    ideal: 'Beverage companies, juice brands, energy drink manufacturers, and bottled water labels.',
  },
  {
    id: 'agriculture-product-ads',
    emoji: '🌾',
    title: 'Agriculture Product Ads',
    subtitle: 'Creative promotional videos for agricultural products, machinery, fertilizers, seeds, and agribusinesses.',
    description: 'Agriculture deserves creative storytelling too. We produce professional videos for agribusinesses — from product demos of machinery to promotional content for fertilizers, seeds, and farming solutions.',
    benefits: ['Equipment demo videos', 'Field & farm cinematography', 'B2B promotional content', 'Technical product explanations'],
    ideal: 'Agribusinesses, farm equipment manufacturers, fertilizer companies, and seed distributors.',
  },
  {
    id: 'product-demo-videos',
    emoji: '📦',
    title: 'Product Demo Videos',
    subtitle: 'Clearly demonstrate your product\'s features and benefits with engaging video presentations.',
    description: 'Product demo videos are one of the most effective ways to show customers exactly what your product does. We create clear, engaging demonstrations that highlight key features and address customer pain points.',
    benefits: ['Step-by-step demonstrations', 'Feature highlight reels', 'Problem/solution format', 'Conversion-focused scripting'],
    ideal: 'SaaS companies, physical product brands, and any business launching a new product or feature.',
  },
  {
    id: 'product-unboxing-videos',
    emoji: '📤',
    title: 'Product Unboxing Videos',
    subtitle: 'Create excitement and build customer confidence with realistic unboxing experiences.',
    description: 'Unboxing videos generate anticipation and build trust. Our realistic unboxing content shows customers exactly what to expect — building confidence and reducing purchase anxiety before they buy.',
    benefits: ['Realistic unboxing experience', 'First-impression storytelling', 'Packaging showcase', 'Customer confidence building'],
    ideal: 'eCommerce brands, subscription boxes, and consumer electronics companies.',
  },
  {
    id: 'customer-testimonial-videos',
    emoji: '⭐',
    title: 'Customer Testimonial Videos',
    subtitle: 'Build credibility through authentic customer stories and real-life experiences.',
    description: 'Nothing builds trust like real customer voices. We produce authentic testimonial videos that capture genuine experiences and turn satisfied customers into your most powerful marketing asset.',
    benefits: ['Real customer stories', 'Authentic interview style', 'Credibility & social proof', 'Emotional connection'],
    ideal: 'Any business looking to build social proof and increase conversion rates through authentic customer stories.',
  },
  {
    id: 'social-media-reels',
    emoji: '🎥',
    title: 'Social Media Reels',
    subtitle: 'Short-form vertical videos optimized to maximize engagement across every platform.',
    description: 'Short-form video dominates social media. Our reels are crafted specifically for Instagram, TikTok, and YouTube Shorts — designed to stop the scroll, drive engagement, and grow your following.',
    benefits: ['Vertical format optimized', 'Trend-aware content', 'High-retention editing', 'Platform-specific strategies'],
    ideal: 'Brands and creators wanting to grow their social media presence and engagement through short-form video.',
  },
  {
    id: 'meta-video-ads',
    emoji: '📢',
    title: 'Meta Video Ads',
    subtitle: 'Performance-focused video ads designed to generate leads, sales, and measurable ROI.',
    description: 'Facebook and Instagram ads require a unique creative approach. We design performance-focused video ads that capture attention in-feed and drive measurable actions — from clicks to conversions.',
    benefits: ['Conversion-focused design', 'Facebook & Instagram optimized', 'A/B test-ready variations', 'ROI-driven creatives'],
    ideal: 'Businesses running Meta ad campaigns who want higher ROAS and better-performing video creatives.',
  },
  {
    id: 'tiktok-video-ads',
    emoji: '🎵',
    title: 'TikTok Video Ads',
    subtitle: 'Trend-driven creative content designed to capture attention and go viral.',
    description: 'TikTok rewards creativity and authenticity. Our TikTok ad production team stays on top of trends, sounds, and formats to create content that feels native to the platform while driving real business results.',
    benefits: ['Trend-aware content', 'Native TikTok aesthetics', 'High-engagement editing', 'Viral potential focus'],
    ideal: 'Brands targeting Gen Z and Millennials through TikTok advertising and organic content.',
  },
  {
    id: 'ecommerce-product-videos',
    emoji: '🛒',
    title: 'eCommerce Product Videos',
    subtitle: 'High-converting videos crafted specifically for Shopify, WooCommerce, and online stores.',
    description: 'Product pages with video convert better. We create eCommerce-optimized product videos that showcase your items from every angle, demonstrate use, and give customers the confidence to buy.',
    benefits: ['Shopify & WooCommerce ready', 'Multi-angle product展示', 'Use-case demonstrations', 'Conversion-optimized editing'],
    ideal: 'Online store owners, Shopify merchants, and WooCommerce store operators wanting to boost product page conversions.',
  },
  {
    id: 'amazon-listing-videos',
    emoji: '📦',
    title: 'Amazon Listing Videos',
    subtitle: 'Professional product videos that improve buyer confidence and increase Amazon conversions.',
    description: 'Amazon listings with video perform significantly better. We produce Amazon-compliant product videos that highlight features, demonstrate use, and build the trust needed to win the buy box.',
    benefits: ['Amazon format compliant', 'Feature & benefit focused', 'Buyer confidence building', 'Conversion optimized'],
    ideal: 'Amazon sellers, FBA businesses, and brands wanting to increase conversion rates on their Amazon listings.',
  },
  {
    id: 'ai-ugc-videos',
    emoji: '🤖',
    title: 'AI UGC Videos',
    subtitle: 'Cost-effective AI-powered creator videos that look authentic and scale effortlessly.',
    description: 'Scale your content production without scaling your budget. Our AI-generated UGC videos combine the authenticity of creator content with the efficiency of automation — delivering high-quality videos at a fraction of the cost.',
    benefits: ['Cost-effective production', 'Quick turnaround', 'Authentic AI storytelling', 'Easily scalable'],
    ideal: 'Brands needing high-volume, affordable UGC-style content for testing and scaling ad campaigns.',
  },
  {
    id: 'motion-graphics-animation',
    emoji: '🎞️',
    title: 'Motion Graphics & Animation',
    subtitle: 'Eye-catching animated videos that simplify your message and strengthen your brand identity.',
    description: 'Sometimes the best way to explain a complex idea is through animation. Our motion graphics team creates visually stunning animated videos that simplify your message and leave a lasting impression.',
    benefits: ['Custom 2D/3D animation', 'Complex idea simplification', 'Brand-aligned design', 'Engaging visual storytelling'],
    ideal: 'Tech companies, SaaS brands, and businesses needing explainer videos or animated brand content.',
  },
  {
    id: 'professional-video-editing',
    emoji: '✂️',
    title: 'Professional Video Editing',
    subtitle: 'Transform raw footage into polished, engaging videos ready for social media and advertising.',
    description: 'Great footage deserves great editing. Our professional video editing service takes your raw clips and transforms them into polished, engaging content — with color grading, sound design, captions, and motion graphics.',
    benefits: ['Professional color grading', 'Sound design & mixing', 'Caption & subtitle addition', 'Motion graphics integration'],
    ideal: 'Content creators, agencies, and businesses who need professional post-production for their video content.',
  },
  {
    id: 'creative-ad-strategy',
    emoji: '📈',
    title: 'Creative Ad Strategy',
    subtitle: 'Data-driven concepts and scripts built to maximize campaign performance and ROI.',
    description: 'Behind every great ad is a great strategy. Our creative ad strategy service delivers data-backed concepts, compelling scripts, and platform-specific approaches designed to maximize your campaign performance.',
    benefits: ['Data-driven creative concepts', 'Professional scriptwriting', 'Platform-specific strategies', 'Performance optimization'],
    ideal: 'Businesses and agencies wanting professional creative direction to improve their ad campaign results.',
  },
];
