import Head from 'next/head';
import Menu from '../components/menu';
import Hero from '../components/hero';
import Footer from '../components/footer';
import Image from 'next/image';

export default function Company() {
  return (
    <>
      <Head>
        <title>About Us | SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>
      <Menu />
      <Hero />

      <div className="container mx-auto">
        <h2 className="mb-5 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none md:text-center">
          Our Story
        </h2>

        <p className="mb-5 text-base text-gray-700 md:text-lg md:text-center">
          SoftGens is a full-service web company dedicated to providing the
          highest quality design, development and online marketing services to
          our clients. Our company is built on the fact that we are a quality
          rather than quantity-based company. Therefore, we only take on
          projects that we fully believe in—projects that meet our needs and
          criteria, and where we are confident we will meet yours.
        </p>
        <p className="mb-5 text-base text-gray-700 md:text-lg md:text-center">
          As a full-service web company, everything is designed, developed and
          marketed by our in-house teams. Founded in 2011 and located in Lahore,
          Pakisan, we began as a web design company but quickly came to
          understand just how many online services our clients really needed and
          how difficult it was for them to have to contract out to so many
          businesses to get it all done. We made the decision to expand into a
          top-of-the-line, full-service web company and have never looked back
          since. Our commitment and determination to be the best in our class is
          the driving force behind our continued growth and success, and we
          continuously challenge ourselves to learn and grow even more than we
          already have. Our team takes great pride in using their vast pool of
          skills and experience to meet the online needs of any company
          regardless of their size or industry.
        </p>
      </div>

      <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
        <div className="grid grid-cols-2 row-gap-8 md:grid-cols-4">
          <div className="text-center md:border-r">
            <h6 className="text-4xl font-bold lg:text-5xl xl:text-6xl">1268</h6>
            <p className="text-sm font-medium tracking-widest text-gray-800 uppercase lg:text-base">
              PROJECTS
            </p>
          </div>
          <div className="text-center md:border-r">
            <h6 className="text-4xl font-bold lg:text-5xl xl:text-6xl">
              199060
            </h6>
            <p className="text-sm font-medium tracking-widest text-gray-800 uppercase lg:text-base">
              LINES OF CODE
            </p>
          </div>
          <div className="text-center md:border-r">
            <h6 className="text-4xl font-bold lg:text-5xl xl:text-6xl">350</h6>
            <p className="text-sm font-medium tracking-widest text-gray-800 uppercase lg:text-base">
              CLIENTS
            </p>
          </div>
          <div className="text-center">
            <h6 className="text-4xl font-bold lg:text-5xl xl:text-6xl">10</h6>
            <p className="text-sm font-medium tracking-widest text-gray-800 uppercase lg:text-base">
              YEARS EXPERIENCE
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
        <div className="grid gap-6 row-gap-10 lg:grid-cols-2">
          <div className="lg:py-6 lg:pr-16">
            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-4 text-gray-600"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <line
                        fill="none"
                        strokeMiterlimit="10"
                        x1="12"
                        y1="2"
                        x2="12"
                        y2="22"
                      ></line>
                      <polyline
                        fill="none"
                        strokeMiterlimit="10"
                        points="19,15 12,22 5,15"
                      ></polyline>
                    </svg>
                  </div>
                </div>
                <div className="w-px h-full bg-gray-300"></div>
              </div>
              <div className="pt-1 pb-8">
                <p className="mb-2 text-lg font-bold">Planning And Analysis</p>
                <p className="text-gray-700">
                  The first and most important part of our process. Our team of
                  professionals collaborate with you so we can fully understand
                  your business needs, goals and objectives. Here at SWS,
                  analysis is an ongoing process as your project evolves from
                  conceptualization to the final product. This way, we not only
                  enhance the business solutions we provide to you, but provide
                  you with a variety of alternatives to choose from
                </p>
              </div>
            </div>
            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-4 text-gray-600"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <line
                        fill="none"
                        strokeMiterlimit="10"
                        x1="12"
                        y1="2"
                        x2="12"
                        y2="22"
                      ></line>
                      <polyline
                        fill="none"
                        strokeMiterlimit="10"
                        points="19,15 12,22 5,15"
                      ></polyline>
                    </svg>
                  </div>
                </div>
                <div className="w-px h-full bg-gray-300"></div>
              </div>
              <div className="pt-1 pb-8">
                <p className="mb-2 text-lg font-bold">
                  Selection And Designing
                </p>
                <p className="text-gray-700">
                  Our team works closely with you to present all the information
                  and options available to you so you can pick the right design
                  plan for your business. We understand that there is no such
                  thing as a cookie-cutter business; your company is unique and
                  has specific needs. Therefore, we provide you with endless
                  designs, constantly revising until both you and our team are
                  100% satisfied.
                </p>
              </div>
            </div>
            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-4 text-gray-600"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <line
                        fill="none"
                        strokeMiterlimit="10"
                        x1="12"
                        y1="2"
                        x2="12"
                        y2="22"
                      ></line>
                      <polyline
                        fill="none"
                        strokeMiterlimit="10"
                        points="19,15 12,22 5,15"
                      ></polyline>
                    </svg>
                  </div>
                </div>
                <div className="w-px h-full bg-gray-300"></div>
              </div>
              <div className="pt-1 pb-8">
                <p className="mb-2 text-lg font-bold">
                  Development And Testing
                </p>
                <p className="text-gray-700">
                  This is where our team gets down to the nitty-gritty and
                  starts shaping your custom solutions into reality. Again, we
                  make sure you are involved in every step of the process, and
                  we will never make any changes without your approval. The
                  development phase and testing phase are concurrent; we test
                  each development as we go along to save time and be as
                  efficient as possible. Our analysts then provide us with
                  follow-up feedback, which we then implement accordingly.
                  Afterwards, you are given a chance to review the end product
                  and request any final changes or touch-ups as needed.
                </p>
              </div>
            </div>
            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-4 text-gray-600"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <line
                        fill="none"
                        strokeMiterlimit="10"
                        x1="12"
                        y1="2"
                        x2="12"
                        y2="22"
                      ></line>
                      <polyline
                        fill="none"
                        strokeMiterlimit="10"
                        points="19,15 12,22 5,15"
                      ></polyline>
                    </svg>
                  </div>
                </div>
                <div className="w-px h-full bg-gray-300"></div>
              </div>
              <div className="pt-1 pb-8">
                <p className="mb-2 text-lg font-bold">
                  Implementation and Integration
                </p>
                <p className="text-gray-700">
                  The moment of truth. After going through our rigorous testing
                  and development phase, it’s time to take you live on the World
                  Wide Web. We make sure your website is accessible, that
                  everything is working correctly and is integrated with back
                  end databases for your security and peace of mind.
                </p>
              </div>
            </div>

            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-4 text-gray-600"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <line
                        fill="none"
                        strokeMiterlimit="10"
                        x1="12"
                        y1="2"
                        x2="12"
                        y2="22"
                      ></line>
                      <polyline
                        fill="none"
                        strokeMiterlimit="10"
                        points="19,15 12,22 5,15"
                      ></polyline>
                    </svg>
                  </div>
                </div>
                <div className="w-px h-full bg-gray-300"></div>
              </div>
              <div className="pt-1 pb-8">
                <p className="mb-2 text-lg font-bold">
                  Maintenance and Support
                </p>
                <p className="text-gray-700">
                  As businesses expand and evolve, their needs change. We offer
                  a variety of maintenance packages to ensure your website gets
                  the customization and maintenance that is so necessary to
                  survive in the online business world. We also offer a 3 month
                  period of warranty which includes website code bug fixing, and
                  begins as soon as your website or software is launched.
                </p>
              </div>
            </div>

            <div className="flex">
              <div className="flex flex-col items-center mr-4">
                <div>
                  <div className="flex items-center justify-center w-10 h-10 border rounded-full">
                    <svg
                      className="w-6 text-gray-600"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <polyline
                        fill="none"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        points="6,12 10,16 18,8"
                      ></polyline>
                    </svg>
                  </div>
                </div>
              </div>
              <div className="pt-1">
                <p className="mb-2 text-lg font-bold">Success</p>
                <p className="text-gray-700"></p>
              </div>
            </div>
          </div>
          <div className="relative">
            <Image
              className="inset-0 object-cover object-bottom w-full rounded shadow-lg h-96 lg:absolute lg:h-full"
              src="https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260"
              alt=""
            />
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
