import Head from 'next/head';
import Menu from '../components/menu';
import Hero from '../components/hero';
import Footer from '../components/footer';
import ContactUs from '../components/contactus';

export default function Company() {
  return (
    <>
      <Head>
        <title>About Us | SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>
      <Menu />
      <Hero />
      <ContactUs />
      <Footer />
    </>
  );
}
