import Head from 'next/head';
import Menu from '../components/menu';
import Link from 'next/link';
import Footer from '../components/footer';
import ContactUs from '../components/contactus';

export default function ContactMe() {
  return (
    <>
      <Head>
        <title>Contact Us | SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>
      <Menu />
      <div className="bg-hero relative overflow-hidden">
        <div className="container flex  items-center justify-between px-4 lg:px-0 py-44  mx-auto flex-col-reverse lg:flex-row static overflow-hidden">
          <div className=" bg-gradient-to-l from-blue-300 to-blue-500 w-[250px] h-[250px] rounded-full absolute -top-20 -left-20 opacity-50"></div>
          <div className="w-full mt-10 lg:w-1/2 lg:mr-0">
            <h2 className="p-2 text-4xl font-extrabold leading-tight text-gray-900 lg:text-5xl font-fira">
              GET IN Touch
            </h2>

            <p className="p-2 mt-4 text-lg text-gray-700 font-fira lg:pr-20 ">
              We’d love to help bring your ideas to life. Ready to take the
              first step?
            </p>
            <div className="flex p-2 mt-6 lg:p-0">
              <Link href="/contact">
                <a className="p-4 text-white font-semibold uppercase rounded-full pl-7 pr-7 hover:text-black bg-gradient-to-l from-blue-300 to-blue-500">
                  00 92 302 6006 280
                </a>
              </Link>
              <Link href="/contact">
                <a className="p-4 ml-6 text-gray-800 uppercase border-2 border-gray-800 rounded-full pl-7 pr-7 hover:bg-gradient-to-l from-blue-300 to-blue-500">
                  info@softgens.com
                </a>
              </Link>
            </div>
          </div>
          <img
            alt="moto"
            src="/images/heroimg.png"
            className="lg:absolute md:block right-0"
            width="765"
            height="558"
          />
        </div>
      </div>
      <ContactUs />
      <Footer />
    </>
  );
}
