import Head from 'next/head';
import Menu from '../components/menu';
import Hero from '../components/hero';
import Work from '../components/work';
import SucessStories from '../components/stories';
import Footer from '../components/footer';
import ContactUs from '../components/contactus';
import Clients from '../components/clients';

export default function Home() {
  return (
    <>
      <Head>
        <title>SoftGens The Way to Next Generation </title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>

      <Menu />
      <Hero />
      <Clients />
      <Work />
      <SucessStories />
      <ContactUs />
      <Footer />
    </>
  );
}
