import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';

export default function Home() {
  const [toggle, SetToggle] = useState(false);
  return (
    <>
      <Head>
        <title>SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>

      <div className="bg-hero">
        <div className="container relative flex flex-col items-center justify-between min-h-screen mx-auto lg:flex-row ">
          <div className="w-full mt-10 lg:w-1/2 lg:mr-0">
            <h2 className="p-2 text-4xl font-extrabold leading-tight text-gray-900 lg:text-5xl font-fira ">
              Impacting Industry
              <br /> Leaders with Softgens
            </h2>
            <p className="p-2 mt-4 text-lg text-gray-700 font-fira lg:pr-20 ">
              We deliver web development, Custome Development services to global
              businesses since 2012, with 100% project delivery success. Hire
              the best programmers at affordable prices. Our design-focused
              approach and project execution processes help you to deliver the
              right solutions.
            </p>
            <div className="flex p-2 mt-6 lg:p-0">
              <Link href="/contact" className="">
                <a className="p-4 text-white uppercase rounded-full pl-7 pr-7 hover:text-black bg-gradient-to-l from-blue-300 to-blue-500">
                  Start A project
                </a>
              </Link>
              <Link href="/contact" className="">
                <a className="p-4 ml-6 text-gray-800 uppercase border-2 border-gray-800 rounded-full pl-7 pr-7 hover:bg-gradient-to-l from-blue-300 to-blue-500">
                  View portfolio
                </a>
              </Link>
            </div>
          </div>
          <div className="w-full mt-8 lg:w-1/2 lg:mt-0">
            <Image
              src="/images/heroimg.png"
              className="absolute right-0"
              width="872"
              height="572"
            />
          </div>
        </div>
      </div>

      <div className="flex items-center h-24 border-b-2 border-gray-100">
        <nav className="container relative flex items-center justify-between px-5 mx-auto lg:px-0">
          <Link href="/" className="flex-1 ">
            <Image
              src="/images/logo.png"
              alt=""
              className="cursor-pointer "
              width="200"
              height="40"
            />
          </Link>

          <div className="hidden lg:block">
            <ul className="flex flex-col items-center text-lg font-normal tracking-wider text-gray-700 lg:bg-white lg:flex-row font-fira">
              <li>
                <Link href="/services">
                  <a className="ml-16 hover:text-blue-700">Services</a>
                </Link>
              </li>
              <li>
                <Link href="/work">
                  <a className="ml-16 hover:text-blue-700">Work</a>
                </Link>
              </li>
              <li>
                <Link href="/insights">
                  <a className="ml-16 hover:text-blue-700">Insights</a>
                </Link>
              </li>
              <li>
                <Link href="/company">
                  <a className="ml-16 hover:text-blue-700">Company</a>
                </Link>
              </li>
              <li>
                <Link href="/contact" className="">
                  <a className="p-4 ml-16 text-white rounded-full pl-7 pr-7 hover:text-blue-700 bg-gradient-to-l from-blue-300 to-blue-500">
                    Contact Us
                  </a>
                </Link>
              </li>
            </ul>
          </div>

          <div
            className={`${toggle ? 'fa-bar' : 'fa-times'} sm:block lg:hidden`}
            onClick={() => SetToggle(!toggle)}
          ></div>
        </nav>
        <div
          className={` ${
            toggle ? 'block' : 'hidden'
          } absolute z-10 block w-full top-24 lg:hidden`}
        >
          {/* <MobileMenu /> */}
        </div>
      </div>
    </>
  );
}
