import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';
import Clients from '../components/clients';
import Service from '../components/service';
import AboutUs from '../components/aboutUs';
import favIon from '../public/images/fav.png' 


export default function Home() {
  return (
    <>
      <Head>
        <title>SoftGens The Way to Next Generation </title>
        <meta name="description" content="Generated by SoftGens" />
        <link rel="icon" href={favIon} />
      </Head>
      <Header 
        title="A digital agency focused on web"
        content="We are a one-stop shop for businesses big and small. From building, to designing, to analyzing and improving, we are always ready to make your company website smarter."
        lottifyURL="https://assets8.lottiefiles.com/packages/lf20_dl87KC.json"
        lottifyWidth="400px"
        lottifyheight="300px"
      />
      <Service/>
      <AboutUs/>
      <Clients />
      <Footer />
    </>
  );
}
