import Head from 'next/head';
import Menu from '../components/menu';
import Link from 'next/link';
import Footer from '../components/footer';
import ContactUs from '../components/contactus';
import Image from 'next/image';

export default function Portfolio() {
  return (
    <>
      <Head>
        <title>Portfolio | SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>
      <Menu />

      <div className="bg-hero">
        <div className="container flex  items-center justify-between py-44  mx-auto flex-row static overflow-hidden">
          <div className="w-full mt-10 lg:w-1/2 lg:mr-0">
            <h2 className="p-2 text-4xl font-extrabold leading-tight text-gray-900 lg:text-5xl font-fira ">
              Sucess Stories
            </h2>
            <p className="p-2 mt-4 text-lg text-gray-700 font-fira lg:pr-20 ">
              Real results, delivered.
            </p>
          </div>
          <Image
            alt="moto"
            src="/images/heroimg.png"
            className="absolute right-0 "
            width="765"
            height="558"
          />
        </div>
      </div>

      <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
        <div className="flex flex-col mb-6 lg:justify-between lg:flex-row md:mb-8">
          <h2 className="max-w-lg mb-5 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none md:mb-6 group">
            <span className="inline-block mb-1 sm:mb-4">
              There is no must in art
              <br className="hidden md:block" />
              because art is free.
            </span>
            <div className="h-1 ml-auto duration-300 origin-left transform bg-deep-purple-accent-400 scale-x-30 group-hover:scale-x-100"></div>
          </h2>
          <p className="text-gray-700 lg:text-sm lg:max-w-md">
            however, according to Reicher, it is not so much class that is dead,
            but rather the absurdity, and some would say the paradigm, of class.
            However, the subject is interpolated into a postpatriarchialist
            dialectic theory that includes consciousness as a totality.
          </p>
        </div>
        <div className="grid gap-6 row-gap-5 mb-8 lg:grid-cols-4 sm:row-gap-6 sm:grid-cols-2">
          <a href="http://mufaqar.com" aria-label="View Item">
            <div className="relative overflow-hidden transition duration-200 transform rounded shadow-lg hover:-translate-y-2 hover:shadow-2xl">
              <Image
                className="object-cover w-full h-56 md:h-64 xl:h-80"
                src="/images/portfolio.jpeg"
                alt=""
                width="500"
                height="600"
              />
              <div className="absolute inset-0 px-6 py-4 transition-opacity duration-200 bg-black bg-opacity-75 opacity-0 hover:opacity-100">
                <p className="mb-4 text-lg font-bold text-gray-100">
                  Mona Lisa
                </p>
                <p className="text-sm tracking-wide text-gray-300">
                  Painted between 1503 and 1517
                </p>
              </div>
            </div>
          </a>
          <a href="http://mufaqar.com" aria-label="View Item">
            <div className="relative overflow-hidden transition duration-200 transform rounded shadow-lg hover:-translate-y-2 hover:shadow-2xl">
              <Image
                className="object-cover w-full h-56 md:h-64 xl:h-80"
                src="/images/portfolio.jpeg"
                alt=""
                width="500"
                height="600"
              />
              <div className="absolute inset-0 px-6 py-4 transition-opacity duration-200 bg-black bg-opacity-75 opacity-0 hover:opacity-100">
                <p className="mb-4 text-lg font-bold text-gray-100">
                  The Starry Night
                </p>
                <p className="text-sm tracking-wide text-gray-300">
                  Vincent Van
                </p>
              </div>
            </div>
          </a>
          <a href="http://mufaqar.com" aria-label="View Item">
            <div className="relative overflow-hidden transition duration-200 transform rounded shadow-lg hover:-translate-y-2 hover:shadow-2xl">
              <Image
                className="object-cover w-full h-56 md:h-64 xl:h-80"
                src="/images/portfolio.jpeg"
                alt=""
                width="500"
                height="600"
              />
              <div className="absolute inset-0 px-6 py-4 transition-opacity duration-200 bg-black bg-opacity-75 opacity-0 hover:opacity-100">
                <p className="mb-4 text-lg font-bold text-gray-100">
                  Portfolio
                </p>
                <p className="text-sm tracking-wide text-gray-300">
                  Opulently gilded and extravagantly patterned Nouveau.
                </p>
              </div>
            </div>
          </a>
          <a href="http://mufaqar.com" aria-label="View Item">
            <div className="relative overflow-hidden transition duration-200 transform rounded shadow-lg hover:-translate-y-2 hover:shadow-2xl">
              <Image
                className="object-cover w-full h-56 md:h-64 xl:h-80"
                src="/images/portfolio.jpeg"
                alt=""
                width="500"
                height="600"
              />
              <div className="absolute inset-0 px-6 py-4 transition-opacity duration-200 bg-black bg-opacity-75 opacity-0 hover:opacity-100">
                <p className="mb-4 text-lg font-bold text-gray-100">
                  The Harvesters
                </p>
                <p className="text-sm tracking-wide text-gray-300">
                  Bruegel’s fanfare for the common man is considered one of the
                  defining works of Western art. This composition was one of six
                  created on the theme of the seasons.
                </p>
              </div>
            </div>
          </a>
        </div>
      </div>

      <ContactUs />
      <Footer />
    </>
  );
}
