import Head from 'next/head';
import Menu from '../components/menu';
import Link from 'next/link';
import Footer from '../components/footer';
import ContactUs from '../components/contactus';
import Image from 'next/image';

export default function Services() {
  return (
    <>
      <Head>
        <title>Services | SoftGens</title>
        <meta name="description" content="Generated by SoftGens" />
      </Head>
      <Menu />
      <div className="bg-hero relative overflow-hidden">
        <div className="container flex  items-center justify-between px-4 lg:px-0 py-44  mx-auto flex-col-reverse lg:flex-row static overflow-hidden">
          <div className=" bg-gradient-to-l from-blue-300 to-blue-500 w-[250px] h-[250px] rounded-full absolute -top-20 -left-20 opacity-50"></div>
          <div className="w-full mt-10 lg:w-1/2 lg:mr-0">
            <h2 className="p-2 text-4xl font-extrabold leading-tight text-gray-900 lg:text-5xl font-fira">
              A digital-first approach to strategy and creative.
            </h2>

            <p className="p-2 mt-4 text-lg text-gray-700 font-fira lg:pr-20 ">
              We are a one-stop shop for businesses big and small. From
              building, to designing, to analyzing and improving, we are always
              ready to make your company website smarter.
            </p>
            <div className="flex p-2 mt-6 lg:p-0">
              <Link href="/contact">
                <a className="p-4 text-white font-semibold uppercase rounded-full pl-7 pr-7 hover:text-black bg-gradient-to-l from-blue-300 to-blue-500">
                  Start A project
                </a>
              </Link>
              <Link href="/contact">
                <a className="p-4 ml-6 text-gray-800 uppercase border-2 border-gray-800 rounded-full pl-7 pr-7 hover:bg-gradient-to-l from-blue-300 to-blue-500">
                  Portfolio
                </a>
              </Link>
            </div>
          </div>
          <Image
            alt="moto"
            src="/images/heroimg.png"
            className="lg:absolute md:block right-0"
            width="765"
            height="558"
          />
        </div>
      </div>

      <div className="container py-16 mx-auto px-10 lg:px-0 lg:py-20">
        <div className="grid gap-5 row-gap-10 lg:grid-cols-2">
          <div className="flex flex-col justify-center">
            <div className="max-w-xl mb-6">
              <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                A digital-first approach to strategy and creative.
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Your story of glory speaks through your brand.We design and give
                a personality, value and competitive edge to your brand. We
                strongly believe that if you are not online, you are not in
                today’s corporate business. We are the creators of good brands
                with a specialized persona and essence of communication. Get
                stunning broachers and flyers specially designed for you.
              </p>
            </div>
            <p className="mb-4 text-sm font-bold tracking-widest uppercase">
              Features
            </p>
            <div className="grid space-y-3 sm:gap-2 sm:grid-cols-2 sm:space-y-0">
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Logo Design And Branding
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Brochure/Flyer Designs
                </li>
              </ul>
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Newsletter And Email Templates
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  All kind of Print And Web Media Designs
                </li>
              </ul>
            </div>
          </div>
          <div>
            <Image
              className="object-cover w-full h-56 rounded shadow-lg sm:h-96"
              src="/images/placeholder.jpg"
              alt=""
              width="560"
              height="560"
            />
          </div>
        </div>
      </div>

      <div className="container py-16 mx-auto px-10 lg:px-0 lg:py-20">
        <div className="grid gap-5 row-gap-10 lg:grid-cols-2">
          <div>
            <Image
              className="object-cover w-full h-56 rounded shadow-lg sm:h-96"
              src="/images/placeholder.jpg"
              alt=""
              width="560"
              height="560"
            />
          </div>

          <div className="flex flex-col justify-center">
            <div className="max-w-xl mb-6">
              <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                Web development
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Reliable, professional and search engine friendly web solutions
                are a need of the today’s web. We build on strong methodologies
                from define design phase to development and deployment. We build
                on footprints of your unique needs. The result is a stable,
                adaptable, organized and user-friendly website for both you and
                customers.More Knocking on Your Virtual business door is our
                target.
              </p>
            </div>
            <p className="mb-4 text-sm font-bold tracking-widest uppercase">
              Features
            </p>
            <div className="grid space-y-3 sm:gap-2 sm:grid-cols-2 sm:space-y-0">
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  CMS and Blog Website Services
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  WooCommerce Development
                </li>
              </ul>
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Website Maintenance
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  E-Commerece Website
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className="container py-16 mx-auto px-10 lg:px-0 lg:py-20">
        <div className="grid gap-5 row-gap-10 lg:grid-cols-2">
          <div className="flex flex-col justify-center">
            <div className="max-w-xl mb-6">
              <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                Designing and Branding
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Your story of glory speaks through your brand.We design and give
                a personality, value and competitive edge to your brand. We
                strongly believe that if you are not online, you are not in
                today’s corporate business. We are the creators of good brands
                with a specialized persona and essence of communication. Get
                stunning broachers and flyers specially designed for you.
              </p>
            </div>
            <p className="mb-4 text-sm font-bold tracking-widest uppercase">
              Features
            </p>
            <div className="grid space-y-3 sm:gap-2 sm:grid-cols-2 sm:space-y-0">
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Logo Design and Branding
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Brochure/Flyer Designs
                </li>
              </ul>
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Newsletter and Email Templates
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  All kind of Print And Web Media Designs
                </li>
              </ul>
            </div>
          </div>
          <div>
            <Image
              className="object-cover w-full h-56 rounded shadow-lg sm:h-96"
              src="/images/placeholder.jpg"
              alt=""
              width="560"
              height="560"
            />
          </div>
        </div>
      </div>
      <div className="container py-16 mx-auto px-10 lg:px-0 lg:py-20">
        <div className="grid gap-5 row-gap-10 lg:grid-cols-2">
          <div>
            <Image
              className="object-cover w-full h-56 rounded shadow-lg sm:h-96"
              src="/images/placeholder.jpg"
              alt=""
              width="560"
              height="560"
            />
          </div>

          <div className="flex flex-col justify-center">
            <div className="max-w-xl mb-6">
              <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                Web development
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Reliable, professional and search engine friendly web solutions
                are a need of the today’s web. We build on strong methodologies
                from define design phase to development and deployment. We build
                on footprints of your unique needs. The result is a stable,
                adaptable, organized and user-friendly website for both you and
                customers.More Knocking on Your Virtual business door is our
                target.
              </p>
            </div>
            <p className="mb-4 text-sm font-bold tracking-widest uppercase">
              Features
            </p>
            <div className="grid space-y-3 sm:gap-2 sm:grid-cols-2 sm:space-y-0">
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  CMS and Blog Website Services
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  WooCommerce Development
                </li>
              </ul>
              <ul className="space-y-3">
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  Website Maintenance
                </li>
                <li className="flex">
                  <span className="mr-1">
                    <svg
                      className="w-5 h-5 mt-px text-deep-purple-accent-400"
                      stroke="currentColor"
                      viewBox="0 0 52 52"
                    >
                      <polygon
                        strokeWidth="4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        fill="none"
                        points="29 13 14 29 25 29 23 39 38 23 27 23"
                      ></polygon>
                    </svg>
                  </span>
                  E-Commerece Website
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <ContactUs />
      <Footer />
    </>
  );
}
